"""Phase 3: point-in-time fundamentals (quarterly/annual versions keyed by filing date),
earnings calendar, insider transactions, daily Fundamentals Grade, pattern detections and the
owner's pattern reviews.

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-05 14:23:51.201217
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0004'
down_revision: str | Sequence[str] | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings_calendar',
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('timing', sa.String(length=16), nullable=False),
    sa.Column('accession', sa.String(length=25), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_earnings_calendar_ticker_id_tickers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticker_id', 'report_date', name=op.f('pk_earnings_calendar'))
    )
    op.create_table('fundamental_grades',
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('path', sa.String(length=16), nullable=False),
    sa.Column('basis', sa.String(length=16), nullable=False),
    sa.Column('coverage_pct', sa.Float(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_fundamental_grades_ticker_id_tickers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticker_id', 'date', name=op.f('pk_fundamental_grades'))
    )
    op.create_table('fundamentals_annual',
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('reported_date', sa.Date(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.SmallInteger(), nullable=True),
    sa.Column('fiscal_period', sa.String(length=4), nullable=True),
    sa.Column('form', sa.String(length=16), nullable=True),
    sa.Column('accession', sa.String(length=25), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('eps_diluted', sa.Float(), nullable=True),
    sa.Column('eps_basic', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('operating_income', sa.Float(), nullable=True),
    sa.Column('equity', sa.Float(), nullable=True),
    sa.Column('derived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_fundamentals_annual_ticker_id_tickers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticker_id', 'period_end', 'reported_date', name=op.f('pk_fundamentals_annual'))
    )
    op.create_table('fundamentals_quarterly',
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('reported_date', sa.Date(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.SmallInteger(), nullable=True),
    sa.Column('fiscal_period', sa.String(length=4), nullable=True),
    sa.Column('form', sa.String(length=16), nullable=True),
    sa.Column('accession', sa.String(length=25), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('eps_diluted', sa.Float(), nullable=True),
    sa.Column('eps_basic', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('operating_income', sa.Float(), nullable=True),
    sa.Column('equity', sa.Float(), nullable=True),
    sa.Column('derived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_fundamentals_quarterly_ticker_id_tickers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticker_id', 'period_end', 'reported_date', name=op.f('pk_fundamentals_quarterly'))
    )
    op.create_table('insider_transactions',
    sa.Column('accession', sa.String(length=25), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('insider_cik', sa.String(length=10), nullable=False),
    sa.Column('insider_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=160), nullable=False),
    sa.Column('is_director', sa.Boolean(), nullable=False),
    sa.Column('is_officer', sa.Boolean(), nullable=False),
    sa.Column('is_ten_percent_owner', sa.Boolean(), nullable=False),
    sa.Column('code', sa.String(length=1), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_insider_transactions_ticker_id_tickers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('accession', 'seq', 'ticker_id', name=op.f('pk_insider_transactions'))
    )
    op.create_index('ix_insider_transactions_ticker_date', 'insider_transactions', ['ticker_id', 'transaction_date'], unique=False)
    op.create_index('ix_fundamental_grades_date', 'fundamental_grades', ['date'], unique=False)
    op.create_table('patterns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('pivot', sa.Float(), nullable=False),
    sa.Column('base_low', sa.Float(), nullable=True),
    sa.Column('depth_pct', sa.Float(), nullable=True),
    sa.Column('duration_weeks', sa.Float(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('base_number', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('status_date', sa.Date(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('swings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contractions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_detected', sa.Date(), nullable=False),
    sa.Column('last_seen', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_patterns_ticker_id_tickers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patterns')),
    sa.UniqueConstraint('ticker_id', 'type', 'timeframe', 'start_date', name=op.f('uq_patterns_ticker_id'))
    )
    op.create_index('ix_patterns_last_seen', 'patterns', ['last_seen'], unique=False)
    op.create_table('pattern_reviews',
    sa.Column('pattern_id', sa.BigInteger(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], name=op.f('fk_pattern_reviews_pattern_id_patterns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pattern_id', name=op.f('pk_pattern_reviews'))
    )
    op.add_column('tickers', sa.Column('fundamentals_refreshed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickers', 'fundamentals_refreshed_at')
    op.drop_table('pattern_reviews')
    op.drop_index('ix_patterns_last_seen', table_name='patterns')
    op.drop_table('patterns')
    op.drop_index('ix_insider_transactions_ticker_date', table_name='insider_transactions')
    op.drop_index('ix_fundamental_grades_date', table_name='fundamental_grades')
    op.drop_table('insider_transactions')
    op.drop_table('fundamentals_quarterly')
    op.drop_table('fundamentals_annual')
    op.drop_table('fundamental_grades')
    op.drop_table('earnings_calendar')
    # ### end Alembic commands ###
