"""Phase 4: setups (one active per stock) with their stage history, the immutable signal log
and signal outcomes.

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-05 15:35:36.729623
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0005'
down_revision: str | Sequence[str] | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('pattern_type', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('state_since', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('first_seen', sa.Date(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('pivot', sa.Float(), nullable=True),
    sa.Column('base_low', sa.Float(), nullable=True),
    sa.Column('readiness_pct', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.Column('regime_multiplier', sa.Float(), nullable=False),
    sa.Column('penalties', sa.Float(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('red_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trade_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('breakout_date', sa.Date(), nullable=True),
    sa.Column('best_grade', sa.String(length=2), nullable=True),
    sa.Column('closed_on', sa.Date(), nullable=True),
    sa.Column('closed_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], name=op.f('fk_setups_pattern_id_patterns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_setups_ticker_id_tickers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_setups'))
    )
    op.create_index('ix_setups_state', 'setups', ['state', 'active'], unique=False)
    op.create_index('uq_setups_active_ticker', 'setups', ['ticker_id'], unique=True, postgresql_where=sa.text('active'))
    op.create_table('setup_transitions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('setup_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('from_state', sa.String(length=16), nullable=True),
    sa.Column('to_state', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['setup_id'], ['setups.id'], name=op.f('fk_setup_transitions_setup_id_setups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_setup_transitions'))
    )
    op.create_index(op.f('ix_setup_transitions_setup_id'), 'setup_transitions', ['setup_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=True),
    sa.Column('setup_id', sa.BigInteger(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('pivot', sa.Float(), nullable=True),
    sa.Column('entry', sa.Float(), nullable=True),
    sa.Column('stop', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['setup_id'], ['setups.id'], name=op.f('fk_signals_setup_id_setups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_signals_ticker_id_tickers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals')),
    sa.UniqueConstraint('date', 'type', 'ticker_id', name=op.f('uq_signals_date'), postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_signals_date'), 'signals', ['date'], unique=False)
    op.create_index('ix_signals_ticker_date', 'signals', ['ticker_id', 'date'], unique=False)
    op.create_table('signal_outcomes',
    sa.Column('signal_id', sa.BigInteger(), nullable=False),
    sa.Column('sessions_observed', sa.Integer(), nullable=False),
    sa.Column('ret_1', sa.Float(), nullable=True),
    sa.Column('ret_5', sa.Float(), nullable=True),
    sa.Column('ret_10', sa.Float(), nullable=True),
    sa.Column('ret_20', sa.Float(), nullable=True),
    sa.Column('ret_60', sa.Float(), nullable=True),
    sa.Column('mfe_pct', sa.Float(), nullable=True),
    sa.Column('mae_pct', sa.Float(), nullable=True),
    sa.Column('stop_hit_on', sa.Date(), nullable=True),
    sa.Column('target_2r_on', sa.Date(), nullable=True),
    sa.Column('gain_20_on', sa.Date(), nullable=True),
    sa.Column('complete', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_signal_outcomes_signal_id_signals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('signal_id', name=op.f('pk_signal_outcomes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signal_outcomes')
    op.drop_index('ix_signals_ticker_date', table_name='signals')
    op.drop_index(op.f('ix_signals_date'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_setup_transitions_setup_id'), table_name='setup_transitions')
    op.drop_table('setup_transitions')
    op.drop_index('uq_setups_active_ticker', table_name='setups', postgresql_where=sa.text('active'))
    op.drop_index('ix_setups_state', table_name='setups')
    op.drop_table('setups')
    # ### end Alembic commands ###
